### ISSUE TITLE
Params `values` option float range and enums

### ISSUE THREAD

**Issue by azhi** [tim-vandecasteele/grape-swagger#233]
Setting param `values` option to float range makes the gem fail.

E.g. param:
`requires :field, type: Float, values: 1.0..10.0`

Exception & bt:
```
Rack app error: #<TypeError: can't iterate from Float>
/home/azhi/.rvm/gems/ruby-2.1.3/gems/activesupport-4.1.1/lib/active_support/core_ext/range/each.rb:7:in `each'
/home/azhi/.rvm/gems/ruby-2.1.3/gems/activesupport-4.1.1/lib/active_support/core_ext/range/each.rb:7:in `each_with_time_with_zone'
/home/azhi/.rvm/gems/ruby-2.1.3/gems/grape-swagger-0.10.1/lib/grape-swagger.rb:208:in `to_a'
/home/azhi/.rvm/gems/ruby-2.1.3/gems/grape-swagger-0.10.1/lib/grape-swagger.rb:208:in `block in parse_params'
/home/azhi/.rvm/gems/ruby-2.1.3/gems/grape-swagger-0.10.1/lib/grape-swagger.rb:179:in `each'
/home/azhi/.rvm/gems/ruby-2.1.3/gems/grape-swagger-0.10.1/lib/grape-swagger.rb:179:in `map'
/home/azhi/.rvm/gems/ruby-2.1.3/gems/grape-swagger-0.10.1/lib/grape-swagger.rb:179:in `parse_params'
/home/azhi/.rvm/gems/ruby-2.1.3/gems/grape-swagger-0.10.1/lib/grape-swagger.rb:571:in `block (3 levels) in setup'
/home/azhi/.rvm/gems/ruby-2.1.3/gems/grape-swagger-0.10.1/lib/grape-swagger.rb:555:in `map'
/home/azhi/.rvm/gems/ruby-2.1.3/gems/grape-swagger-0.10.1/lib/grape-swagger.rb:555:in `block (2 levels) in setup'
/home/azhi/.rvm/gems/ruby-2.1.3/gems/grape-swagger-0.10.1/lib/grape-swagger.rb:554:in `each'
/home/azhi/.rvm/gems/ruby-2.1.3/gems/grape-swagger-0.10.1/lib/grape-swagger.rb:554:in `block in setup'
/home/azhi/.rvm/gems/ruby-2.1.3/gems/grape-0.11.0/lib/grape/endpoint.rb:47:in `call'
/home/azhi/.rvm/gems/ruby-2.1.3/gems/grape-0.11.0/lib/grape/endpoint.rb:47:in `block in generate_api_method'
/home/azhi/.rvm/gems/ruby-2.1.3/gems/grape-0.11.0/lib/grape/endpoint.rb:247:in `call'
/home/azhi/.rvm/gems/ruby-2.1.3/gems/grape-0.11.0/lib/grape/endpoint.rb:247:in `run'
/home/azhi/.rvm/gems/ruby-2.1.3/gems/grape-0.11.0/lib/grape/endpoint.rb:195:in `block in call!'
...
```

This behaviour was introduced in https://github.com/tim-vandecasteele/grape-swagger/commit/2ac951f42c3c1471d0d1ec27ad2979101880ddf5#diff-3bdef0e908741c1b55e8e9660610e33dR101. 
My guess is parsing `values` range into enum should only be done if value in range responds to `:succ`, or even explicitly whitelist range value types to `Integer` and `String`.

**Comment by dblock** [comment]
Looks legit. Would appreciate a spec + fix.

**Comment by azhi** [comment]
Ok, fixed float ranges bug.

However, after thinking about it for a while, i believe that converting ranges to enum in docs might not be the best idea.
Suppose you have an integer field with `values: 1..1_000_000`. I don't think you would like to have around 7 Mb JSON doc with all numbers between 1 and 1_000_000.
